/* eslint-disable react/no-unescaped-entities */
import Link from "next/link";
import { ArrowRight, Building2, Check, MapPin } from "lucide-react";
import { Breadcrumbs } from "@/components/layout/breadcrumbs";
import { ServiceContactCTA } from "@/components/sections/service-contact-cta";
import { highRiseHub, specialistServices } from "@/data/specialist-services";
import { siteConfig } from "@/lib/site-config";

export function HighRiseHubPage() {
  const path = `/services/${highRiseHub.slug}`;
  const capabilities = ["Exterior painting and refurbishment", "Glass, cladding and façade cleaning", "Re-siliconing and sealant repairs", "Rope access plastering and crack repairs", "Concrete repair and masonry restoration", "High-rise roof repairs", "Gondola painting, cleaning and repairs"];
  const schema = { "@context": "https://schema.org", "@type": "Service", "@id": `${siteConfig.siteUrl}${path}#service`, name: "High-Rise, Rope Access & Gondola Services", serviceType: "High-rise building maintenance", url: `${siteConfig.siteUrl}${path}`, description: highRiseHub.description, provider: { "@id": `${siteConfig.siteUrl}/#business` }, areaServed: ["Colombo", "Greater Colombo"] };
  return <>
    <div className="bg-[var(--soft)]"><div className="site-container py-7"><Breadcrumbs current="High-Rise & Rope Access" path={path} /></div><section className="site-container grid gap-10 pb-16 pt-5 lg:grid-cols-[1.15fr_.85fr] lg:items-center lg:pb-24"><div><p className="eyebrow">High-rise & access services</p><h1 className="mt-4 max-w-5xl text-[clamp(2.5rem,6vw,5.5rem)] font-black leading-[.98] tracking-[-.06em] text-balance">{highRiseHub.h1}</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-[var(--muted)]">ABLE provides specialist access options for suitable exterior maintenance, painting, cleaning and repair work on apartments, condominiums, offices, commercial buildings and other managed multi-storey properties.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/?service=Rope%20Access%20Painting#contact" className="btn btn-primary">Request a site assessment <ArrowRight aria-hidden="true" className="h-4 w-4" /></Link><Link href="/service-areas" className="btn btn-secondary"><MapPin aria-hidden="true" className="h-4 w-4" />Service areas</Link></div></div><aside className="rounded-[1.75rem] bg-[#151714] p-7 text-white sm:p-9"><Building2 aria-hidden="true" className="h-10 w-10 text-orange-300" /><h2 className="mt-7 text-2xl font-black">Choosing an access method</h2><p className="mt-4 text-sm leading-7 text-white/65">Rope access may be practical where conventional access is difficult. A building service gondola may suit a property with appropriate infrastructure. Building design, access, scope, site conditions and safety requirements are reviewed before a method is agreed.</p></aside></section></div>
    <section className="section-space"><div className="site-container"><p className="eyebrow">Choose the right service</p><h2 className="mt-4 max-w-3xl text-3xl font-black tracking-[-.04em] sm:text-5xl">Four clear routes for high-rise exterior work</h2><div className="mt-10 grid gap-4 md:grid-cols-2">{specialistServices.map((service) => <Link key={service.slug} href={`/services/${service.slug}`} className="group rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-6 shadow-[var(--shadow-sm)] hover:border-orange-300"><p className="eyebrow">{service.eyebrow}</p><h3 className="mt-4 text-2xl font-black tracking-[-.03em]">{service.shortTitle}</h3><p className="mt-3 text-sm leading-7 text-[var(--muted)]">{service.description}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-extrabold text-[var(--orange)]">Explore service <ArrowRight aria-hidden="true" className="h-4 w-4 transition group-hover:translate-x-1" /></span></Link>)}</div></div></section>
    <section className="section-space bg-[var(--soft)]"><div className="site-container grid gap-10 lg:grid-cols-2"><div><p className="eyebrow">Specialist capability</p><h2 className="mt-4 text-3xl font-black tracking-[-.04em] sm:text-4xl">Exterior maintenance at height</h2><p className="mt-5 leading-8 text-[var(--muted)]">Depending on the property and the agreed scope, ABLE can consider painting, cleaning, plastering, remedial repairs and sealant maintenance in difficult-access areas.</p><ul className="mt-7 grid gap-3">{capabilities.map((item) => <li key={item} className="flex items-start gap-3 font-bold leading-7"><Check aria-hidden="true" className="mt-1 h-5 w-5 shrink-0 text-[var(--orange)]" />{item}</li>)}</ul></div><div><p className="eyebrow">Enquiry and assessment</p><h2 className="mt-4 text-3xl font-black tracking-[-.04em] sm:text-4xl">Information that helps with the first review</h2><p className="mt-5 leading-8 text-[var(--muted)]">Send the building location, property type, recent photographs, the affected elevations or areas, and a description of the required finish or repair. A site assessment may then be arranged to confirm access suitability and scope.</p><p className="mt-6 rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-6 leading-8 text-[var(--muted)]">From ABLE's base in Attidiya, Dehiwala, the team handles suitable property-maintenance and high-rise access enquiries across Colombo and Greater Colombo.</p></div></div></section>
    <ServiceContactCTA service="Rope Access Painting" /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} />
  </>;
}
