import Link from "next/link";
import { ArrowRight, Check, ClipboardCheck, MapPin, ShieldCheck } from "lucide-react";
import type { SpecialistService } from "@/data/specialist-services";
import { specialistServiceBySlug } from "@/data/specialist-services";
import { Breadcrumbs } from "@/components/layout/breadcrumbs";
import { ServiceContactCTA } from "@/components/sections/service-contact-cta";
import { siteConfig } from "@/lib/site-config";

export function SpecialistServicePage({ service }: { service: SpecialistService }) {
  const path = `/services/${service.slug}`;
  const schema = { "@context": "https://schema.org", "@type": "Service", "@id": `${siteConfig.siteUrl}${path}#service`, name: service.shortTitle, serviceType: service.shortTitle, url: `${siteConfig.siteUrl}${path}`, description: service.description, provider: { "@id": `${siteConfig.siteUrl}/#business` }, areaServed: [{ "@type": "AdministrativeArea", name: "Colombo" }, { "@type": "AdministrativeArea", name: "Greater Colombo" }] };
  return <>
    <div className="bg-[var(--soft)]">
      <div className="site-container py-7"><Breadcrumbs current={service.shortTitle} path={path} /></div>
      <section className="site-container grid gap-10 pb-16 pt-5 lg:grid-cols-[1.18fr_.82fr] lg:items-center lg:pb-24">
        <div><p className="eyebrow">{service.eyebrow}</p><h1 className="mt-4 max-w-4xl text-[clamp(2.5rem,6vw,5.4rem)] font-black leading-[.98] tracking-[-.06em] text-balance">{service.h1}</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-[var(--muted)]">{service.intro}</p><div className="mt-8 flex flex-wrap gap-3"><Link href={`/?service=${encodeURIComponent(service.quoteService)}#contact`} className="btn btn-primary">Request a quote <ArrowRight aria-hidden="true" className="h-4 w-4" /></Link><Link href="/service-areas" className="btn btn-secondary"><MapPin aria-hidden="true" className="h-4 w-4" />View service areas</Link></div></div>
        <aside className="relative overflow-hidden rounded-[1.75rem] bg-[#151714] p-7 text-white shadow-[var(--shadow-raised)] sm:p-9"><div className="grid-texture absolute inset-0 opacity-30" /><div className="relative"><ShieldCheck aria-hidden="true" className="h-9 w-9 text-orange-300" /><h2 className="mt-7 text-2xl font-black tracking-[-.03em]">Access is reviewed for each site</h2><p className="mt-4 text-sm leading-7 text-white/65">The appropriate working method depends on the building design, access, scope, site conditions and safety requirements. Rope access or gondola access is not assumed to suit every property.</p></div></aside>
      </section>
    </div>
    <section className="section-space"><div className="site-container grid gap-12 lg:grid-cols-2"><div><p className="eyebrow">What the service can include</p><h2 className="mt-4 text-3xl font-black tracking-[-.04em] sm:text-4xl">A scope matched to the exterior work</h2><ul className="mt-8 grid gap-3">{service.includes.map((item) => <li key={item} className="flex items-start gap-3 rounded-xl border border-[var(--line)] bg-[var(--surface)] p-4"><Check aria-hidden="true" className="mt-0.5 h-5 w-5 shrink-0 text-[var(--orange)]" /><span className="font-bold leading-7">{item}</span></li>)}</ul></div><div><p className="eyebrow">Assessment considerations</p><h2 className="mt-4 text-3xl font-black tracking-[-.04em] sm:text-4xl">What ABLE reviews before work is agreed</h2><ul className="mt-8 space-y-4">{service.considerations.map((item) => <li key={item} className="flex items-start gap-3 text-base leading-8 text-[var(--muted)]"><ClipboardCheck aria-hidden="true" className="mt-1 h-5 w-5 shrink-0 text-sky-500" />{item}</li>)}</ul><p className="mt-8 rounded-2xl bg-[var(--soft)] p-6 text-sm leading-7 text-[var(--muted)]">Based in Attidiya, Dehiwala, ABLE handles suitable {service.shortTitle.toLowerCase()} enquiries across Colombo and Greater Colombo. Availability and attendance depend on the property, scope and scheduling.</p></div></div></section>
    <section className="section-space bg-[var(--soft)]"><div className="site-container"><p className="eyebrow">From enquiry to quotation</p><h2 className="mt-4 text-3xl font-black tracking-[-.04em] sm:text-4xl">A practical review before work begins</h2><ol className="mt-9 grid gap-4 lg:grid-cols-3">{service.process.map((step, index) => <li key={step} className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-6"><span className="text-sm font-black text-[var(--orange)]">0{index + 1}</span><p className="mt-4 leading-8 text-[var(--muted)]">{step}</p></li>)}</ol></div></section>
    <section className="section-space"><div className="site-container grid gap-12 lg:grid-cols-[1fr_.85fr]"><div><p className="eyebrow">Common questions</p><h2 className="mt-4 text-3xl font-black tracking-[-.04em] sm:text-4xl">Useful details before you enquire</h2><div className="mt-8 divide-y divide-[var(--line)]">{service.faqs.map((faq) => <div key={faq.question} className="py-6"><h3 className="text-lg font-black">{faq.question}</h3><p className="mt-3 leading-8 text-[var(--muted)]">{faq.answer}</p></div>)}</div></div><aside><p className="eyebrow">Related high-rise services</p><div className="mt-5 grid gap-3">{service.related.map((slug) => { const related = specialistServiceBySlug(slug); return related ? <Link key={slug} href={`/services/${slug}`} className="group flex items-center justify-between gap-4 rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-5 font-black hover:border-orange-300"><span>{related.shortTitle}</span><ArrowRight aria-hidden="true" className="h-4 w-4 text-[var(--orange)] transition group-hover:translate-x-1" /></Link> : null; })}<Link href="/services/high-rise-rope-access" className="group flex items-center justify-between gap-4 rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-5 font-black hover:border-orange-300"><span>All high-rise & access services</span><ArrowRight aria-hidden="true" className="h-4 w-4 text-[var(--orange)] transition group-hover:translate-x-1" /></Link></div></aside></div></section>
    <ServiceContactCTA service={service.quoteService} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} />
  </>;
}
