/* eslint-disable react/no-unescaped-entities */
import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, MapPin } from "lucide-react";
import { getSiteContent } from "@/backend/content-repository";
import { Footer } from "@/components/layout/footer";
import { Header } from "@/components/layout/header";

export const metadata: Metadata = { title: { absolute: "Property Maintenance Service Areas Colombo | ABLE" }, description: "ABLE serves suitable property-maintenance and high-rise access enquiries from Attidiya and Dehiwala across Colombo and Greater Colombo.", alternates: { canonical: "/service-areas" }, openGraph: { type: "website", url: "/service-areas", title: "ABLE Service Areas | Colombo & Greater Colombo", description: "Property maintenance and specialist high-rise access coverage from ABLE.", images: [{ url: "/opengraph-image", alt: "ABLE Property Maintenance service areas" }] }, twitter: { card: "summary_large_image", images: ["/opengraph-image"] } };

const areas = [
  { title: "Attidiya & Dehiwala", text: "ABLE is based in Attidiya, Dehiwala, and considers general maintenance, renovation and suitable high-rise access enquiries in the local area." },
  { title: "Mount Lavinia & Ratmalana", text: "Property owners, landlords and managers can enquire about repairs, refurbishment, exterior painting and appropriate difficult-access work." },
  { title: "Colombo", text: "ABLE handles suitable residential, commercial, office, apartment and managed-property enquiries across Colombo, subject to scope and scheduling." },
  { title: "Nugegoda", text: "General property care and specialist exterior access enquiries are reviewed according to the building, work required and practical access." },
  { title: "Moratuwa", text: "Maintenance, renovation and high-rise exterior enquiries can be submitted with the property location and photographs for an initial review." },
  { title: "Rajagiriya & Battaramulla", text: "ABLE considers suitable work for homes, commercial buildings and multi-storey managed properties in these Greater Colombo areas." },
  { title: "Greater Colombo", text: "Coverage extends across the practical Greater Colombo service area. Attendance is confirmed only after the location, scope, access and availability are reviewed." },
];

export default async function ServiceAreasPage() {
  const content = await getSiteContent();
  return <><a className="skip-link" href="#main-content">Skip to content</a><Header business={content.business} navigation={content.navigation} homeLinks /><main id="main-content"><section className="bg-[var(--soft)]"><div className="site-container pb-16 pt-14 sm:pb-24 sm:pt-20"><p className="eyebrow">Service areas</p><h1 className="mt-4 max-w-5xl text-[clamp(2.7rem,7vw,6rem)] font-black leading-[.96] tracking-[-.065em]">Property maintenance across Colombo and Greater Colombo</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-[var(--muted)]">From ABLE's base in Attidiya, Dehiwala, the team handles suitable property-maintenance and high-rise access enquiries across Colombo and Greater Colombo. Service depends on the property, scope, access and scheduling.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/services" className="btn btn-primary">Explore services <ArrowRight aria-hidden="true" className="h-4 w-4" /></Link><Link href="/#contact" className="btn btn-secondary">Request a quote</Link></div></div></section><section className="section-space"><div className="site-container grid gap-4 md:grid-cols-2 lg:grid-cols-3">{areas.map((area) => <article key={area.title} className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-6"><MapPin aria-hidden="true" className="h-6 w-6 text-[var(--orange)]" /><h2 className="mt-5 text-xl font-black">{area.title}</h2><p className="mt-3 text-sm leading-7 text-[var(--muted)]">{area.text}</p></article>)}</div></section><section className="section-space bg-[#151714] text-white"><div className="site-container grid gap-8 lg:grid-cols-2"><div><p className="eyebrow text-orange-300">General property services</p><h2 className="mt-4 text-3xl font-black">Repairs, upkeep and renovation</h2><p className="mt-4 leading-8 text-white/65">ABLE supports suitable plumbing, electrical, painting, fitting, flooring, carpentry, outdoor maintenance, refurbishment and landlord-maintenance enquiries.</p></div><div><p className="eyebrow text-orange-300">High-rise & access work</p><h2 className="mt-4 text-3xl font-black">Exterior work on suitable multi-storey buildings</h2><p className="mt-4 leading-8 text-white/65">Rope access painting, building repairs, glass and cladding cleaning, re-siliconing, and gondola services are assessed according to each property.</p><Link href="/services/high-rise-rope-access" className="mt-5 inline-flex items-center gap-2 font-extrabold text-orange-300">Explore high-rise services <ArrowRight aria-hidden="true" className="h-4 w-4" /></Link></div></div></section></main><Footer business={content.business} navigation={content.navigation} homeLinks /></>;
}
