import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { getSiteContent } from "@/backend/content-repository";
import { Breadcrumbs } from "@/components/layout/breadcrumbs";
import { Footer } from "@/components/layout/footer";
import { Header } from "@/components/layout/header";
import { ServiceIcon } from "@/components/ui/service-icon";
import { specialistServices } from "@/data/specialist-services";

export const metadata: Metadata = { title: { absolute: "Property Maintenance & High-Rise Services Colombo | ABLE" }, description: "Explore ABLE property maintenance, renovation, rope access and gondola services across Colombo and Greater Colombo.", alternates: { canonical: "/services" }, openGraph: { type: "website", url: "/services", title: "Property Maintenance & High-Rise Services Colombo | ABLE", description: "General property maintenance and specialist high-rise access services from ABLE.", images: [{ url: "/opengraph-image", alt: "ABLE Property Maintenance services" }] }, twitter: { card: "summary_large_image", images: ["/opengraph-image"] } };

export default async function ServicesPage() {
  const content = await getSiteContent();
  return <><a className="skip-link" href="#main-content">Skip to content</a><Header business={content.business} navigation={content.navigation} homeLinks /><main id="main-content"><div className="bg-[var(--soft)]"><div className="site-container py-7"><Breadcrumbs current="All services" path="/services" /></div><section className="site-container pb-16 pt-5 sm:pb-24"><p className="eyebrow">Services</p><h1 className="mt-4 max-w-5xl text-[clamp(2.7rem,7vw,6rem)] font-black leading-[.96] tracking-[-.065em]">Property maintenance and specialist high-rise services</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-[var(--muted)]">Choose everyday property maintenance, a planned renovation or specialist exterior work at height. Every enquiry is reviewed against the property, scope and access required.</p></section></div>
    <section className="section-space"><div className="site-container"><p className="eyebrow">Property maintenance & renovation</p><h2 className="mt-4 text-3xl font-black tracking-[-.04em] sm:text-4xl">General services for homes and managed properties</h2><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{content.services.map((service) => <Link key={service.title} href={`/?service=${encodeURIComponent(service.title)}#contact`} className="group rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-5 hover:border-orange-300"><ServiceIcon name={service.icon} /><h3 className="mt-5 text-lg font-black">{service.title}</h3><p className="mt-2 text-sm leading-7 text-[var(--muted)]">{service.text}</p><span className="mt-4 inline-flex items-center gap-2 text-sm font-extrabold text-[var(--orange)]">Request this service <ArrowRight aria-hidden="true" className="h-4 w-4" /></span></Link>)}</div></div></section>
    <section className="section-space bg-[#151714] text-white"><div className="site-container"><p className="eyebrow text-orange-300">High-rise & access services</p><h2 className="mt-4 text-3xl font-black tracking-[-.04em] sm:text-5xl">Specialist exterior access for suitable buildings</h2><div className="mt-9 grid gap-4 md:grid-cols-2">{specialistServices.map((service) => <Link key={service.slug} href={`/services/${service.slug}`} className="group rounded-2xl border border-white/12 bg-white/[.055] p-6 hover:border-orange-300/50"><h3 className="text-2xl font-black">{service.shortTitle}</h3><p className="mt-3 text-sm leading-7 text-white/60">{service.description}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-extrabold text-orange-300">View service <ArrowRight aria-hidden="true" className="h-4 w-4 transition group-hover:translate-x-1" /></span></Link>)}</div><Link href="/services/high-rise-rope-access" className="btn btn-light mt-8">Explore the high-rise service hub <ArrowRight aria-hidden="true" className="h-4 w-4" /></Link></div></section></main><Footer business={content.business} navigation={content.navigation} homeLinks /></>;
}
